import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { verifyAdmin } from '@/lib/auth';

/**
 * GET /api/ai/insights
 * Admin-only: returns AI-derived behavior insights over the last 7 days.
 *   - KPIs: total sessions, events, add_to_cart rate, checkout_complete rate
 *   - Top viewed products (with categories)
 *   - Persona distribution
 *   - Upsell funnel: shown -> clicked -> added
 *   - Daily AI summary text (generated by the LLM)
 */
export async function GET(req: NextRequest) {
  const admin = await verifyAdmin(req);
  if (!admin) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  const [sessions, events, addToCart, checkoutStart, checkoutComplete] = await Promise.all([
    db.userSession.count({
      where: { updatedAt: { gte: since } },
    }),
    db.userEvent.count({
      where: { createdAt: { gte: since } },
    }),
    db.userEvent.count({
      where: { type: 'add_to_cart', createdAt: { gte: since } },
    }),
    db.userEvent.count({
      where: { type: 'checkout_start', createdAt: { gte: since } },
    }),
    db.userEvent.count({
      where: { type: 'checkout_complete', createdAt: { gte: since } },
    }),
  ]);

  const upsellShown = await db.userEvent.count({
    where: { type: 'upsell_shown', createdAt: { gte: since } },
  });
  const upsellClicked = await db.userEvent.count({
    where: { type: 'upsell_clicked', createdAt: { gte: since } },
  });
  const upsellAdded = await db.userEvent.count({
    where: { type: 'upsell_added', createdAt: { gte: since } },
  });

  // Top viewed products
  const topViewedRaw = await db.userEvent.groupBy({
    by: ['productId'],
    where: {
      type: 'product_view',
      createdAt: { gte: since },
      productId: { not: null },
    },
    _count: true,
    orderBy: { _count: { productId: 'desc' } },
    take: 5,
  });

  const topViewedProducts = await Promise.all(
    topViewedRaw
      .filter((r) => r.productId)
      .map(async (r) => {
        const p = await db.product.findUnique({
          where: { id: r.productId! },
          select: { id: true, name: true, salePrice: true, thumb: true, images: true },
        });
        return p ? { ...p, views: r._count } : null;
      })
  ).then((arr) => arr.filter(Boolean));

  // Persona distribution (derived from intentScore buckets)
  const allSessions = await db.userSession.findMany({
    where: { updatedAt: { gte: since } },
    select: { intentScore: true, budgetTier: true, persona: true },
  });
  const personas: Record<string, number> = {};
  const budgets: Record<string, number> = {};
  let avgIntent = 0;
  for (const s of allSessions) {
    if (s.persona) personas[s.persona] = (personas[s.persona] || 0) + 1;
    else personas['unknown'] = (personas['unknown'] || 0) + 1;
    if (s.budgetTier) budgets[s.budgetTier] = (budgets[s.budgetTier] || 0) + 1;
    avgIntent += s.intentScore;
  }
  if (allSessions.length > 0) avgIntent = avgIntent / allSessions.length;

  // Conversion rate
  const cartRate = sessions > 0 ? (addToCart / sessions) * 100 : 0;
  const checkoutRate = sessions > 0 ? (checkoutComplete / sessions) * 100 : 0;
  const upsellClickRate = upsellShown > 0 ? (upsellClicked / upsellShown) * 100 : 0;
  const upsellAddRate = upsellClicked > 0 ? (upsellAdded / upsellClicked) * 100 : 0;

  return NextResponse.json({
    range: '7d',
    kpis: {
      sessions,
      events,
      addToCart,
      checkoutStart,
      checkoutComplete,
      cartRate: Math.round(cartRate * 10) / 10,
      checkoutRate: Math.round(checkoutRate * 10) / 10,
      avgIntent: Math.round(avgIntent * 100) / 100,
    },
    upsellFunnel: {
      shown: upsellShown,
      clicked: upsellClicked,
      added: upsellAdded,
      clickRate: Math.round(upsellClickRate * 10) / 10,
      addRate: Math.round(upsellAddRate * 10) / 10,
    },
    topViewed: topViewedProducts,
    personas,
    budgets,
  });
}
